apiVersion: apps/v1
kind: Deployment
metadata:
  name: beegoapp-deployment
  labels:
    app: beegoapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beegoapp
  template:
    metadata:
      labels:
        app: beegoapp
    spec:
      containers:
      - name: nginx
        image: chienyuan/beegoapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: beegoapp
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: beegoapp
  type: LoadBalancer


